# Generated by Django 4.2.5 on 2023-09-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("summary", models.TextField()),
                ("image1", models.ImageField(upload_to="dashboard_images/")),
                ("image2", models.ImageField(upload_to="dashboard_images/")),
                ("image3", models.ImageField(upload_to="dashboard_images/")),
                ("image4", models.ImageField(upload_to="dashboard_images/")),
                ("image5", models.ImageField(upload_to="dashboard_images/")),
                ("image6", models.ImageField(upload_to="dashboard_images/")),
            ],
        ),
    ]
